Repository spryker/architecture-sniffer, pull requests merged in 2018-12, with the labels that each got.

#52 DT-279: Implemented rules for joins
  composer.json
  src/Module/ModuleFinder.php
  src/Module/ModuleFinderInterface.php
  src/Module/Transfer/ModuleTransfer.php
  src/Node/DocBlock/CustomTags/ModuleTag.php
  src/Node/DocBlock/Mapper/DocBlockNodeMapper.php
  src/Node/DocBlock/Mapper/DocBlockNodeMapperInterface.php
  src/Node/DocBlock/Reader/DocBlockNodeReader.php
  src/Node/DocBlock/Reader/DocBlockNodeReaderInterface.php
  src/Node/Reader/NodeReader.php
  src/Node/Reader/NodeReaderInterface.php
  src/Path/PathBuilder.php
  src/Path/PathBuilderInterface.php
  src/Path/Transfer/PathTransfer.php
  src/PropelQuery/ClassNode/Transfer/ClassNodeTransfer.php
  src/PropelQuery/Method/MethodFinder.php
  src/PropelQuery/Method/MethodFinderInterface.php
  src/PropelQuery/Method/Transfer/MethodTransfer.php
  src/PropelQuery/Module/ModuleFinder.php
  src/PropelQuery/Module/ModuleFinderInterface.php
  src/PropelQuery/PropelQueryFacade.php
  src/PropelQuery/PropelQueryFacadeInterface.php
  src/PropelQuery/PropelQueryFactory.php
  src/PropelQuery/Query/QueryFinder.php
  src/PropelQuery/Query/QueryFinderInterface.php
  src/PropelQuery/Relation/RelationFinder.php
  src/PropelQuery/Relation/RelationFinderInterface.php
  src/PropelQuery/Schema/PropelSchemaTableFinder.php
  src/PropelQuery/Schema/PropelSchemaTableFinderInterface.php
  src/PropelQuery/Schema/Transfer/PropelSchemaTableRelationTransfer.php
  src/PropelQuery/Schema/Transfer/PropelSchemaTableTransfer.php
  src/Transfer/TransferInterface.php
  src/Zed/Persistence/Repository/AbstractRepositoryRule.php
  src/Zed/Persistence/Repository/RepositoryPropelQueryJoinRule.php
  src/Zed/ruleset.xml
Labels: request review

#57 DT-199: RFC: Reduce scope of Entity Transfers
  .gitignore
  codeception.yml
  src/Zed/Business/Facade/FacadeArgumentsNotAllowedUseEntityTransferRule.php
  src/Zed/Communication/Plugin/PluginArgumentsNotAllowedUseEntityTransferRule.php
  src/Zed/ruleset.xml
  tests/Zed/Business/FacadeArgumentsNotAllowedUseEntityTransferRuleTest.php
  tests/Zed/Communication/Plugin/PluginArgumentsNotAllowedUseEntityTransferRuleTest.php
  tests/Zed/codeception.yml
  tests/_data/Generated/Shared/Transfer/TestModuleEntityTransfer.php
  tests/_data/Generated/Shared/Transfer/TestModuleTransfer.php
  tests/_data/Zed/Business/FacadeArgumentsNotAllowedUseEntityTransferRuleTest/testFacadeMethodDoesNotHaveEntityTransferArgument.php
  tests/_data/Zed/Business/FacadeArgumentsNotAllowedUseEntityTransferRuleTest/testFacadeMethodHasEntityTransferArgument.php
  tests/_data/Zed/Communication/Plugin/PluginArgumentsNotAllowedUseEntityTransferRuleTest/testPluginMethodDoesNotHaveEntityTransferArgument.php
  tests/_data/Zed/Communication/Plugin/PluginArgumentsNotAllowedUseEntityTransferRuleTest/testPluginMethodHasEntityTransferArgument.php
Labels: request review

#60 [DT-194] check RFC: Bridges
  src/Common/Bridge/BridgeMethodsRule.php
  src/Common/Bridge/BridgeNameRule.php
  src/Common/Bridge/BridgePathRule.php
  src/Common/ruleset.xml
  tests/Common/Bridge/BridgeMethodsTest.php
  tests/Common/Bridge/BridgeNameTest.php
  tests/Common/Bridge/BridgePathTest.php
  tests/Common/codeception.yml
  tests/Shared/_support/SharedTester.php
  tests/Shared/_support/_generated/SharedTesterActions.php
  tests/_bootstrap.php
  tests/_data/Common/Bridge/BridgeMethodsTest/testRuleAppliesWhenBridgeMethodsAreNotCorrect.php
  tests/_data/Common/Bridge/BridgeMethodsTest/testRuleDoesNotApplyWhenBridgeMethodsAreCorrect.php
  tests/_data/Common/Bridge/BridgeNameTest/testRuleAppliesWhenBridgeNameIsNotCorrect.php
  tests/_data/Common/Bridge/BridgeNameTest/testRuleDoesNotApplyWhenBridgeNameIsCorrect.php
  tests/_data/Common/Bridge/BridgePathTest/testRuleAppliesWhenBridgePathIsNotCorrect.php
  tests/_data/Common/Bridge/BridgePathTest/testRuleDoesNotApplyWhenBridgePathIsCorrect.php
Labels: feature

#58 DT-200: Implemented RFC - Repository for Persistence Layer
  src/Zed/Persistence/Repository/RepositoryCanUseSpyEntityRule.php
  src/Zed/ruleset.xml
  tests/Zed/Persistence/Repository/RepositoryCanUseSpyEntityRuleTest.php
  tests/Zed/codeception.yml
  tests/_data/Orm/Zed/Persistence/SpyTestEntity.php
  tests/_data/Zed/Persistence/Repository/RepositoryCanUseSpyEntityRuleTest/testFacadeCanNotCreateSpyEntity.php
  tests/_data/Zed/Persistence/Repository/RepositoryCanUseSpyEntityRuleTest/testRepositoryCanCreateSpyEntity.php
Labels: request review

#55 [DT-193] Implement rules for the environment constants. Added tests.
  codeception.yml
  src/Shared/ModuleConstantsFormingConstantValuesRule.php
  src/Shared/ModuleConstantsPathRule.php
  src/Shared/ModuleConstantsTypeRule.php
  src/Shared/ruleset.xml
  tests/Shared/ModuleConstants/ModuleConstantsTest.php
  tests/Shared/codeception.yml
  tests/_data/Shared/ModuleConstants/ModuleConstantsTest/testRuleAppliesWhenModuleConstantsIsNotInterface.php
  tests/_data/Shared/ModuleConstants/ModuleConstantsTest/testRuleAppliesWhenModuleConstantsLiesNotInSharedDirectory.php
  tests/_data/Shared/ModuleConstants/ModuleConstantsTest/testRuleDoesNotApplyWhenModuleConstantsHasCorrectConstantValues.php
Labels: feature

#61 [DT-196] check RFC: Extension modules on new plugin creation
  src/Common/Plugin/AbstractPluginRule.php
  src/Common/Plugin/NewPluginExtensionModuleRule.php
  src/Common/ruleset.xml
  src/SprykerAbstractRule.php
  tests/Common/Plugin/NewPluginExtensionModuleTest.php
  tests/_bootstrap.php
  tests/_data/Common/Plugin/NewPluginExtensionModuleTest/testRuleAppliesWhenPluginImplementsNotExtensionModuleInterface.php
  tests/_data/Common/Plugin/NewPluginExtensionModuleTest/testRuleDoesNotApplyWhenPluginImplementsExtensionModuleInterface.php
Labels: feature, request review

#59 DT-5: architecture sniffer support approved RFC#1
  composer.json
  src/Common/DependencyProvider/AbstractDependencyProviderRule.php
  src/Common/Factory/FactoryGetContainNoNewRule.php
  src/Common/Factory/FactoryOnlyGetAndCreateRule.php
  src/Common/Factory/FactoryPropelQueryMethodNameRule.php
  src/Common/ruleset.xml
  src/Module/ModuleFinder.php
  src/Module/ModuleFinderInterface.php
  src/Module/Transfer/ModuleTransfer.php
  src/Node/DocBlock/CustomTags/ModuleTag.php
  src/Node/DocBlock/Mapper/DocBlockNodeMapper.php
  src/Node/DocBlock/Mapper/DocBlockNodeMapperInterface.php
  src/Node/DocBlock/Reader/DocBlockNodeReader.php
  src/Node/DocBlock/Reader/DocBlockNodeReaderInterface.php
  src/Node/Reader/NodeReader.php
  src/Node/Reader/NodeReaderInterface.php
  src/Path/PathBuilder.php
  src/Path/PathBuilderInterface.php
  src/Path/Transfer/PathTransfer.php
  src/PropelQuery/ClassNode/Transfer/ClassNodeTransfer.php
  src/PropelQuery/Method/MethodFinder.php
  src/PropelQuery/Method/MethodFinderInterface.php
  src/PropelQuery/Method/Transfer/MethodTransfer.php
  src/PropelQuery/Module/ModuleFinder.php
  src/PropelQuery/Module/ModuleFinderInterface.php
  src/PropelQuery/PropelQueryFacade.php
  src/PropelQuery/PropelQueryFacadeInterface.php
  src/PropelQuery/PropelQueryFactory.php
  src/PropelQuery/Query/QueryFinder.php
  src/PropelQuery/Query/QueryFinderInterface.php
  src/PropelQuery/Relation/RelationFinder.php
  src/PropelQuery/Relation/RelationFinderInterface.php
  src/PropelQuery/Schema/PropelSchemaTableFinder.php
  src/PropelQuery/Schema/PropelSchemaTableFinderInterface.php
  src/PropelQuery/Schema/Transfer/PropelSchemaTableRelationTransfer.php
  src/PropelQuery/Schema/Transfer/PropelSchemaTableTransfer.php
  src/Transfer/TransferInterface.php
  src/Zed/DependencyProvider/DependencyProviderPropelQueryConstantNameRule.php
  src/Zed/DependencyProvider/DependencyProviderPropelQueryMethodNameRule.php
  src/Zed/Persistence/Repository/AbstractRepositoryRule.php
  src/Zed/Persistence/Repository/RepositoryPropelQueryJoinRule.php
  src/Zed/ruleset.xml
Labels: ready-for-release, request review

#66 [DT-192] Added static call of create method to exceptions
  src/Common/Factory/FactoryCreateContainOneNewRule.php
Labels: bug, prio

#65 Bugfix
  src/Common/Bridge/BridgeMethodsRule.php
  src/Common/Bridge/BridgeNameRule.php
  src/Common/Bridge/BridgePathRule.php
  src/Common/Plugin/NewPluginExtensionModuleRule.php
  src/Zed/Persistence/Repository/RepositoryCanUseSpyEntityRule.php
Labels: bug, prio
